### ISSUE TITLE
insmod: ERROR: could not insert module tcp_ledbat.ko: Invalid parameters

### ISSUE THREAD

**Issue by brentadamson** [silviov/TCP-LEDBAT#4]
Hi,

I am unable to load the module:

`$ sudo insmod tcp_ledbat.ko`

`insmod: ERROR: could not insert module tcp_ledbat.ko: Invalid parameters`

I am running Linux Mint 19.2

**Comment by brentadamson** [comment]
$ dmesg | tail
[   82.389542] tcp_ledbat: loading out-of-tree module taints kernel.
[   82.389596] tcp_ledbat: module verification failed: signature and/or required key missing - tainting kernel
[   82.391608] TCP: ledbat does not implement required ops
[  104.018582] TCP: ledbat does not implement required ops

**Comment by brentadamson** [comment]
I'm not sure if this is the proper solution, but seems to work:

```
diff --git a/src/Makefile b/src/Makefile
index b1a8dd8..7709886 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -3,7 +3,7 @@ IDIR= /lib/modules/$(shell uname -r)/kernel/net/ipv4/
 KDIR := /lib/modules/$(shell uname -r)/build
 PWD := $(shell pwd)
 default:
-       $(MAKE) -C $(KDIR) SUBDIRS=$(PWD) modules
+       $(MAKE) -C $(KDIR) M=$(PWD) modules

 install:
        install -v -m 644 tcp_ledbat.ko $(IDIR)


diff --git a/src/tcp_ledbat.c b/src/tcp_ledbat.c
index 456f6ff..77f57d7 100644
--- a/src/tcp_ledbat.c
+++ b/src/tcp_ledbat.c
@@ -508,6 +508,7 @@ static struct tcp_congestion_ops tcp_ledbat = {
        .init = tcp_ledbat_init,
        .ssthresh = tcp_ledbat_ssthresh,
        .cong_avoid = tcp_ledbat_cong_avoid,
+       .undo_cwnd  = tcp_reno_undo_cwnd,
        .pkts_acked = tcp_ledbat_pkts_acked,
        .release = tcp_ledbat_release,```

**Comment by dtaht** [comment]
I note that I have not cared about this module for years. So if it works, great. If it's still correct, I have no idea. We showed that ledbat didn't work right in an age of fq or AQM here: 

https://perso.telecom-paristech.fr/drossi/paper/rossi14comnet-b.pdf

and I think it's largely ceased to matter.
