### ISSUE TITLE
ERROR: could not insert 'tcp_ledbat

### ISSUE THREAD

**Issue by rgilangn** [silviov/TCP-LEDBAT#8]
i cant install TCP_LEDBAT on Ubuntu 18 kernel 4.15. the message shows :
```
modprobe tcp_ledbat
modprobe: ERROR: could not insert 'tcp_ledbat': Invalid argument
Makefile:9: recipe for target 'install' failed
make: *** [install] Error 1
```
![rsz_screenshot_from_2020-01-27_19-19-41](https://user-images.githubusercontent.com/46716703/73174688-f3a7f200-413a-11ea-9e08-f04e9e9dfdc4.jpg)

**Comment by pwilloughby** [comment]
You need the patch from https://github.com/silviov/TCP-LEDBAT/issues/4  Additionally tcp_time_stamp has changed in your newer kernel.  I have a patch in the works for the 5.3 kernel that I suspect will work on 4.15.

**Comment by rgilangn** [comment]
heyho after long time i try to fix it and i try your suggestion and its works, but it must download manually from your branch. thanks a lot

![image](https://user-images.githubusercontent.com/46716703/74841263-0046f100-535b-11ea-9fa3-be9cfffee0c3.png)
